#!/bin/bash

set -e
set -u
set -x

find . \
     -name .coverage -prune -o \
     -name .eggs -prune -o \
     -name .git -prune -o \
     -name .hg -prune -o \
     -name .tox -prune -o \
     -name .venv -prune -o \
     -name \*.egg-info -prune -o \
     -name __pycache__ -prune -o \
     -name __snapshots__ -prune -o \
     -name _build -prune -o \
     -name _vendor -prune -o \
     -name vendor -prune -o \
     -name venv -prune -o \
     -not -name \*.bz2 \
     -not -name \*.gif \
     -not -name \*.gz \
     -not -name \*.jpeg \
     -not -name \*.jpg \
     -not -name \*.ldif \
     -not -name \*.lzma \
     -not -name \*.mo \
     -not -name \*.mov \
     -not -name \*.pdf \
     -not -name \*.pem \
     -not -name \*.png \
     -not -name \*.pyc \
     -not -name \*.svg \
     -not -name \*.whl \
     -not -name \*.woff \
     -not -name \*.woff2 \
     -not -name \*.xls \
     -not -name \*.xlsx \
     -not -name \*.xz \
     -type f \
     -exec emacs -Q -batch {} \
     -eval "(setq require-final-newline t)" \
     -eval "(set-buffer-modified-p t)" \
     -eval "(require 'whitespace)" \
     -eval "(let ((whitespace-style '(empty trailing))) (whitespace-cleanup))" \
     -f save-buffer \;
