#!/bin/bash

set -e
set -u
set -x

find . \
     -name .coverage -prune -o \
     -name .git -prune -o \
     -name .hg -prune -o \
     -name .tox -prune -o \
     -name \*.egg-info -prune -o \
     -name __pycache__ -prune -o \
     -name __snapshots__ -prune -o \
     -not -name \*.gif \
     -not -name \*.jpg \
     -not -name \*.ldif \
     -not -name \*.mo \
     -not -name \*.pem \
     -not -name \*.png \
     -not -name \*.pyc \
     -not -name \*.woff2 \
     -not -name \*.xls \
     -not -name \*.xlsx \
     -type f \
     -exec emacs -Q -batch {} -eval "(require 'whitespace)" -eval "(let ((whitespace-style '(empty trailing))) (whitespace-cleanup))" -f save-buffer \;
